image: node:12.22

stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_PROJECT_ID"
  untracked: true
  paths:
    - node_modules

run_build:
  stage: build
  script:
    - npm install

run_lint:
  stage: test
  script:
    - npm run lint

run_test:
  stage: test
  script:
    - npm test

deploy_production:
  stage: deploy
  script:
    - npm config set user 0
    - npm config set unsafe-perm true
    - npm install -g serverless
    - sls deploy
  environment:
    name: prod
  only:
    - master
